site_name: JANUS
site_url: https://fwl-janus.readthedocs.io
repo_url: https://github.com/FormingWorlds/JANUS
repo_name: GitHub

nav:
  - Home: index.md
  - Install: getting_started.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Source code: https://github.com/FormingWorlds/CALLIOPE
  - Issues page: https://github.com/FormingWorlds/CALLIOPE/issues
  - 🔗 PROTEUS: https://fwl-proteus.readthedocs.io/
  - 🔗 CALLIOPE: https://fwl-calliope.readthedocs.io/
  - 🔗 ZEPHYRUS: https://github.com/FormingWorlds/ZEPHYRUS/
  - 🔗 MORS: https://fwl-mors.readthedocs.io/
  - 🔗 AGNI: https://h-nicholls.space/AGNI/
  - 🔗 LovePy: https://github.com/nichollsh/lovepy
  - 🔗 VULCAN: https://github.com/FormingWorlds/VULCAN
  - 🔗 Zalmoxis: https://zalmoxis.readthedocs.io/
  - 🔗 Aragog: https://github.com/FormingWorlds/aragog
  - 🔗 SPIDER: https://github.com/djbower/spider


theme:
  name: material
  palette:
    primary: black
    accent: deep orange

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- mkdocstrings:
    # https://mkdocstrings.github.io/usage/
    handlers:
      python:
        paths: [src]
        import:
        - https://installer.readthedocs.io/en/stable/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://docs.scipy.org/doc/scipy/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        - https://matplotlib.org/stable/objects.inv
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          show_source: true
          show_root_heading: false
          show_root_full_path: false
          docstring_section_style: list
          members_order: alphabetical
          merge_init_into_class: yes
          filters: ["!^_"]

watch:
  - src/
  - docs/
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
