#! /bin/bash
# Script to set-up and make the radiation code

here=`pwd`
host=`uname -n`

SRC_LIST="general modules_gen aux scatter correlated_k"
SRC_LIST=${SRC_LIST}" modules_core radiance_core"
SRC_LIST=${SRC_LIST}" illumination interface_core"
SRC_LIST=${SRC_LIST}" nlte"

echo 'Building the radiation code in bin/ and utilities in sbin/'
date

# Build the C utilities in sbin
cd sbin
make
cd $here

# Create the bin directory and copy across files
mkdir -p bin
cp make/* bin
for SRCDIR in $SRC_LIST
do
  cd src/$SRCDIR
  FILE_LIST=`ls *.f* 2> /dev/null`
  for FILE in $FILE_LIST
  do
    if [ $FILE -nt $here/bin/$FILE ]
      then
        cp $FILE $here/bin/$FILE
    fi
  done
  FILE_LIST=`ls *.F90 2> /dev/null`
  for FILE in $FILE_LIST
  do
    ppfile=$here/bin/${FILE%F90}f90
    if [ $FILE -nt $ppfile ]
      then
        cp $FILE $ppfile
    fi
  done
  cd $here
done

# Build the source code in bin
cd bin
./mkdep
make $1 && echo "All compiled OK"
cd $here

echo "Setting path to distribution in set_rad_env"
sed "s#???#${here}#" sbin/set_rad_env_tmp > set_rad_env
grep "LIBCDF_PATH" bin/Mk_cmd | \
sed 's/ *LIBCDF_PATH *= */LIBCDF_PATH=/' >> set_rad_env
echo 'export LD_LIBRARY_PATH=$LIBCDF_PATH:$LD_LIBRARY_PATH' >> set_rad_env

date

exit 0
