import os
import numpy as np

# Define data and code directories
dir_continua    = "../dat_continua/"
dir_hitran      = "../dat_hitran/"
dir_hitemp      = "../dat_hitemp/"
dir_socrates    = "/Users/tim/bitbucket/pcd_couple-interior-atmosphere/socrates/socrates_main/"

# Available modes: "production", "testing"
mode            = "testing"

print("########## MODE:", mode, "##########")

# Set band edges depending on mode
if mode == "production":
    
    # HITEMP H2O LbL block spacing
    bands = np.concatenate((np.arange(0,3000,25),np.arange(3000,11000,50),np.arange(11000,30500,500))) 

    # 300 bands
    # bands = np.concatenate((np.arange(0,3000,20),np.arange(3000,9000,50),np.arange(9000,24500,500))) 

    # P-T grids
    pt_lbl = "pt48_reshigh"
    pt_cia = "pt_cont_reshigh"

    # Frequency increment for integration in m-1
    i_int  = "0.1"

elif mode == "testing":

    # HITEMP H2O LbL block spacing
    bands = np.concatenate((np.arange(0,3000,25),np.arange(3000,11000,50),np.arange(11000,30500,500))) 
    
    # # 9 bands
    # bands = np.concatenate((np.arange(0,3000,800),np.arange(3000,9000,1500),np.arange(9000,24500,10000))) 
    
    # # 2 bands (for debugging)
    # bands = np.arange(0,24500,10000) 

    # # 1 band (for faster debugging)
    # bands = np.arange(0,24500,20000) 

    # P-T grids
    pt_lbl = "pt48_reslow"
    pt_cia = "pt_cont_reslow"

    # Frequency increment for integration in m-1
    i_int  = "1.0"

# Set first band edge to non-zero, otherwise error
bands[0] = 1.0 

# Number of bands
band_no = str(int(np.size(bands)-1))
print("Number of bands:", band_no)

# Find band indices of band edges compatible with HITEMP data wavenumber spacing
co2_hitemp_band_edges = [ 0, 500, 625, 750, 1000, 1500, 2000, 2125, 2250, 2500, 3000, 3250, 3500, 3750, 4000, 4500, 5000, 5500, 6000, 6500, 12785 ]
h2o_hitemp_band_edges = [ 0, 50, 150, 250, 350, 500, 600, 700, 800, 900, 1000, 1150, 1300, 1500, 1750, 2000, 2250, 2500, 2750, 3000, 3250, 3500, 4150, 4500, 5000, 5500, 6000, 6500, 7000, 7500, 8000, 8500, 9000, 11000, 30000 ]

# Corresponding band edges
co2_band_indices = [0] # Zero because of loop definition (see in HITEMP loop) 
h2o_band_indices = [0]

# Loop over band edges and compare to HITEMP edges
for idx, nu in enumerate(bands):
    if nu in co2_hitemp_band_edges:
        co2_band_indices.append(idx)
    if nu in h2o_hitemp_band_edges:
        h2o_band_indices.append(idx)

# Add last band edge
co2_band_indices.append(np.size(bands)-1) # 12785 not in band edges
# h2o_band_indices.append(np.size(bands)-1) # 30000 already included

print("CO2 HITEMP band edges:", co2_hitemp_band_edges)
print("CO2 HITEMP-compatible band numbers:", co2_band_indices)
print("H2O HITEMP band edges:", h2o_hitemp_band_edges)
print("H2O HITEMP-compatible band numbers:", h2o_band_indices)

# File name
file_name = "sp_all_hitemp_"+band_no

# Remove auxiliary files generated by previous runs
os.system('rm -rf gen_spec_file')
os.system('rm -rf '+file_name)
os.system('rm -rf '+file_name+'_k')
os.system('rm -rf *_lbl')
os.system('rm -rf *_lbl.nc')
os.system('rm -rf *_m')
os.system('rm -rf *_o')
os.system('rm -rf *_o.nc')
os.system('rm -rf *_l')
os.system('rm -rf *h2o_*')
os.system('rm -rf *co2_*')
os.system('rm -rf *ch4_*')
os.system('rm -rf *co_*')
os.system('rm -rf *n2_*')
os.system('rm -rf *o2_*')
os.system('rm -rf *h2_*')

# Open file to produce bash script
f = open("gen_spec_file","w+")

# Write skeleton spectral file using prep_spec utility
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')

# Set number of bands
f.write(band_no + '\n')

# Set total number of absorbers
f.write('7'  + '\n') # 7
# Set absorber ids (see Socrates userguide)
f.write('1'  + '\n')  # H2O
f.write('2'  + '\n')  # CO2
f.write('5'  + '\n')  # CO
f.write('6'  + '\n')  # CH4
f.write('7'  + '\n')  # O2
f.write('13' + '\n')  # N2
f.write('23' + '\n')  # H2

# Set total number of continua
f.write('14' + '\n') # 14
# Set CIA pairs
#   Self:
f.write('7'  + '\n')  # O2-
f.write('7'  + '\n')  # -O2
f.write('13' + '\n')  # N2-
f.write('13' + '\n')  # -N2
f.write('23' + '\n')  # H2-
f.write('23' + '\n')  # -H2
f.write('1'  + '\n')  # H2O-
f.write('1'  + '\n')  # -H2O
f.write('2'  + '\n')  # CO2-
f.write('2'  + '\n')  # -CO2
f.write('6'  + '\n')  # CH4-
f.write('6'  + '\n')  # -CH4
#   Foreign:
f.write('2'  + '\n')  # CO2-
f.write('23' + '\n')  # -H2
f.write('2'  + '\n')  # CO2-
f.write('6'  + '\n')  # -CH4
f.write('7'  + '\n')  # O2-
f.write('13' + '\n')  # -N2
f.write('7'  + '\n')  # O2-
f.write('2'  + '\n')  # -CO2
f.write('13' + '\n')  # N2-
f.write('6'  + '\n')  # -CH4
f.write('13' + '\n')  # N2-
f.write('23' + '\n')  # -H2
f.write('13' + '\n')  # N2-
f.write('1'  + '\n')  # -H2O
f.write('23' + '\n')  # H2-
f.write('6'  + '\n')  # -CH4

# Set number of aerosols
f.write('0'+ '\n')

# Set band units (c for inverse cm)
f.write('c'+ '\n')

# Write band edges one by one
f.write(str(bands[0])+'\n')
for band in bands[1:-1]:
	f.write(str(band)+'\n')
	f.write(str(band)+'\n')
f.write(str(bands[-1])+'\n')

# Set absorbers in each band: line *absorbers IDs*
# Set to '0' when using MT_CKD or HITEMP data!
for band in bands[:-1]:
	f.write('0'+ '\n') # 1 2 5 6 7 13 23

# Set continua in each band: CIA *indexing IDs*
# Set to '0' when using MT_CKD or HITEMP data!
for band in bands[:-1]:
	f.write('0'+ '\n') # 1 2 3 ... 

# Exclude no bands
f.write('n'+ '\n')

# Close prep_spec
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

#####################

# Write correlated-k coefficients using Ccorr_k utility, with suffixes:
# -F File with grid of pressure-temperature values
# -R Range of bands for the calculation (default to all)
# -c Cutoff in inverse cm for each band
# -i Frequency increment for integration in m-1
# -l Maximum absorption path in kg/m2
# -t Tolerance, i.e. maximum RMS error in correlated-k assumption
# -k Adjust for use with CKD continuum (optional)
# -s Spectral file
# +p Planckian weighting
# -lk Use lookup table for pressure/temperature scaling
# -o, -m, -L Output files
# -np Number of processors

########## Line data

# Loop over all HITEMP data packages
f.write("echo '###############   H2O lines – HITEMP   ###############'"+"\n")
for idx, band in enumerate(h2o_band_indices):

    if idx != 0:
        band_first              = str(h2o_band_indices[idx-1]+1)
        band_last               = str(band)
        hitemp_band_edge_left   = str(h2o_hitemp_band_edges[idx-1])
        hitemp_band_edge_right  = str(h2o_hitemp_band_edges[idx])
        band_no_interval        = str(int(band_last)-int(band_first))

        f.write("echo Delete:" + "\n")
        f.write("echo ls *h2o_*" + "\n")
        f.write("rm -rf *h2o_*" + "\n")

        # To check validity
        print("########## H2O bands", band_first+"-"+band_last, "| HITEMP edges:", hitemp_band_edge_left+"-"+hitemp_band_edge_right)
        f.write("echo '##########' H2O bands "+band_first+"-"+band_last+" '|' HITEMP edges: "+hitemp_band_edge_left+"-"+hitemp_band_edge_right+"\n")

        f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitemp+'01_'+hitemp_band_edge_left+'-'+hitemp_band_edge_right+'_HITEMP2010.par -R '+band_first+' '+band_last+' -c 3000.0 -i '+i_int+' -l 1 1.0e1 -b 1.5e-3 -s '+file_name+' +p -lk -k -o h2o_l'+band_no+'_l -m h2o_l'+band_no+'_lm -L h2o_lbl_lwf_'+pt_lbl+'.nc -sm h2o_l'+band_no+'_'+band_first+'-'+band_last+'map.nc'+ '\n')
        f.write('prep_spec <<EOF'+ '\n')
        f.write(file_name+ '\n')
        f.write('a'+ '\n')
        f.write('5'+ '\n')
        f.write('y'+ '\n')
        f.write('h2o_l'+band_no+'_l'+ '\n')
        f.write('-1'+ '\n')
        f.write('EOF'+ '\n')
        f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
        f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
        f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

        # H2O-H2O MT_CKD
        f.write("echo '##########' H2O-H2O MT_CKD "+band_first+"-"+band_last+" '|' HITEMP edges: "+hitemp_band_edge_left+"-"+hitemp_band_edge_right+"\n")
        f.write('Ccorr_k -F '+pt_cia+' -R '+band_first+' '+band_last+' -c 2500.0 -i '+i_int+' -ct 1 1 10.0 -t 1.0e-3 -e '+dir_continua+'mt_ckd_v3.0_s296 '+dir_continua+'mt_ckd_v3.0_s260 -k -s '+file_name+' +p -lk -o h2o-h2o_l'+band_no+'_'+band_first+'-'+band_last+'c -m h2o-h2o_l'+band_no+'_'+band_first+'-'+band_last+'cm -L h2o-h2o_lbl_lw.nc -lw h2o_l'+band_no+'_'+band_first+'-'+band_last+'map.nc'+ '\n')
        # Add to spec file with prep_spec
        f.write('prep_spec <<EOF'+ '\n')
        f.write(file_name + '\n')
        f.write('a'+ '\n')
        # Select block 19 (CIA data)
        f.write('19'+ '\n')
        f.write('y'+ '\n')
        f.write('h2o-h2o_l'+band_no+'_'+band_first+'-'+band_last+'c'+ '\n')
        f.write('-1'+ '\n')
        f.write('EOF'+ '\n')
        # Remove faulty characters
        f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
        f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
        f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# Loop over all HITEMP data packages
f.write("echo '###############   CO2 lines – HITEMP   ###############'"+"\n")
for idx, band in enumerate(co2_band_indices):

    if idx != 0:
        band_first = str(co2_band_indices[idx-1]+1)
        band_last  = str(band)
        hitemp_band_edge_left  = str(co2_hitemp_band_edges[idx-1])
        hitemp_band_edge_right = str(co2_hitemp_band_edges[idx])

        # To check validity
        print("########## CO2 bands", band_first+"-"+band_last, "| HITEMP edges:", hitemp_band_edge_left+"-"+hitemp_band_edge_right)
        f.write("echo '##########' CO2 bands "+band_first+"-"+band_last+" '|' HITEMP edges: "+hitemp_band_edge_left+"-"+hitemp_band_edge_right+"\n")

        f.write("echo Delete:" + "\n")
        f.write("echo ls *co2_*" + "\n")
        f.write("rm -rf *co2_*" + "\n")
       
        f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitemp+'02_'+hitemp_band_edge_left+'-'+hitemp_band_edge_right+'_HITEMP2010.par -R '+band_first+' '+band_last+' -c 3000.0 -i '+i_int+' -l 2 1.0e1 -b 1.5e-3 -s '+file_name+' +p -lk -k -o co2_l'+band_no+'_l -m co2_l'+band_no+'_lm -L co2_lbl_lwf_'+pt_lbl+'.nc -sm co2_l'+band_no+'_'+band_first+'-'+band_last+'map.nc'+ '\n')
        f.write('prep_spec <<EOF'+ '\n')
        f.write(file_name+ '\n')
        f.write('a'+ '\n')
        f.write('5'+ '\n')
        f.write('y'+ '\n')
        f.write('co2_l'+band_no+'_l'+ '\n')
        f.write('-1'+ '\n')
        f.write('EOF'+ '\n')
        f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
        f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
        f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# CH4 lines
f.write("echo '###############   CH4 lines – HITEMP   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitemp+'06_HITEMP2020_provisional_all.par -R 1 '+band_no+' -c 3000.0 -i '+i_int+' -l 6 1.0e1 -t 1.0e-2 -k -s '+file_name+' +p -lk -o ch4_o -m ch4_m -L ch4_lbl.nc -np 2'+ '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('5'+ '\n')
f.write('y'+ '\n')
f.write('ch4_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# CO lines
f.write("echo '###############   CO lines – HITEMP   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitemp+'05_HITEMP2019.par -R 1 '+band_no+' -c 3000.0 -i '+i_int+' -l 5 1.0e1 -t 1.0e-2 -k -s '+file_name+' +p -lk -o co_o -m co_m -L co_lbl.nc -np 2'+ '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('5'+ '\n')
f.write('y'+ '\n')
f.write('co_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# O2 lines
f.write("echo '###############   O2 lines   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitran+'o2_hitran.par -R 1 '+band_no+' -c 3000.0 -i '+i_int+' -l 7 1.0e1 -t 1.0e-2 -k -s '+file_name+' +p -lk -o o2_o -m o2_m -L o2_lbl.nc -np 2'+ '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('5'+ '\n')
f.write('y'+ '\n')
f.write('o2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# H2 lines
f.write("echo '###############   H2 lines   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitran+'h2_hitran.par -R 1 '+band_no+' -c 3000.0 -i '+i_int+' -l 23 1.0e1 -t 1.0e-2 -k -s '+file_name+' +p -lk -o h2_o -m h2_m -L h2_lbl.nc -np 2'+ '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('5'+ '\n')
f.write('y'+ '\n')
f.write('h2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# N2 lines
f.write("echo '###############   N2 lines   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_lbl+' -D '+dir_hitran+'n2_hitran.par -R 1 '+band_no+' -c 3000.0 -i '+i_int+' -l 13 1.0e1 -t 1.0e-2 -k -s '+file_name+' +p -lk -o n2_o -m n2_m -L n2_lbl.nc -np 2'+ '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('5'+ '\n')
f.write('y'+ '\n')
f.write('n2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

########## Self continua

# N2-N2 CIA
f.write("echo '###############   N2-N2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'N2-N2_2018_fixed.cia -R 1 '+band_no+' -i '+i_int+' -ct 13 13 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o n2n2_o -m n2n2_m -L n2n2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('n2n2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# O2-O2 CIA
f.write("echo '###############   O2-O2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'O2-O2_2018b_fixed.cia -R 1 '+band_no+' -i '+i_int+' -ct 7 7 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o o2o2_o -m o2o2_m -L o2o2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('o2o2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# H2-H2 CIA
f.write("echo '###############   H2-H2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'H2-H2_CIA_Borysow_combined.cia -R 1 '+band_no+' -i '+i_int+' -ct 23 23 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o h2h2_o -m h2h2_m -L h2h2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
# Select block 19 (CIA data)
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('h2h2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# CO2-CO2 CIA
f.write("echo '###############   CO2-CO2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'CO2-CO2_2018_fixed.cia -R 1 '+band_no+' -i '+i_int+' -ct 2 2 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o co2co2_o -m co2co2_m -L co2co2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('co2co2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# CH4-CH4 CIA
f.write("echo '###############   CH4-CH4 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'CH4-CH4_2011.cia -R 1 '+band_no+' -i '+i_int+' -ct 6 6 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o ch4ch4_o -m ch4ch4_m -L ch4ch4_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('ch4ch4_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

########## Foreign continua

# CO2-H2 CIA
f.write("echo '###############   CO2-H2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'CO2-H2_2018.cia -R 1 '+band_no+' -i '+i_int+' -ct 2 23 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o co2h2_o -m co2h2_m -L co2h2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('co2h2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')
f.write("sed -i -e 's/          51/           0/g' "+file_name+'\n')

# CO2-CH4 CIA
f.write("echo '###############   CO2-CH4 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'CO2-CH4_2018.cia -R 1 '+band_no+' -i '+i_int+' -ct 2 6 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o co2ch4_o -m co2ch4_m -L co2ch4_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('co2ch4_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters and NaNs
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')
f.write("sed -i -e 's/          51/           0/g' "+file_name+'\n')

# O2-N2 CIA
f.write("echo '###############   O2-N2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'O2-N2_2018_fixed.cia -R 1 '+band_no+' -i '+i_int+' -ct 7 13 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o o2n2_o -m o2n2_m -L o2n2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('o2n2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# O2-CO2 CIA
f.write("echo '###############   O2-CO2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'O2-CO2_2011.cia -R 1 '+band_no+' -i '+i_int+' -ct 7 2 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o o2co2_o -m o2co2_m -L o2co2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('o2co2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# N2-CH4 CIA
f.write("echo '###############   N2-CH4 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'N2-CH4_2011.cia -R 1 '+band_no+' -i '+i_int+' -ct 13 6 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o n2ch4_o -m n2ch4_m -L n2ch4_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('n2ch4_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# N2-H2 CIA
f.write("echo '###############   N2-H2 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'N2-H2_2011.cia -R 1 '+band_no+' -i '+i_int+' -ct 13 23 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o n2h2_o -m n2h2_m -L n2h2_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('n2h2_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# N2-H2O CIA
f.write("echo '###############   N2-H2O CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'N2-H2O_2018.cia -R 1 '+band_no+' -i '+i_int+' -ct 13 1 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o n2h2o_o -m n2h2o_m -L n2h2o_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('n2h2o_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

# H2-CH4 CIA
f.write("echo '###############   H2-CH4 CIA   ###############'"+"\n")
f.write('Ccorr_k -F '+pt_cia+' -CIA '+dir_continua+'H2-CH4_eq_2011.cia -R 1 '+band_no+' -i '+i_int+' -ct 23 6 1.0e2 -t 1.0e-2 -s '+file_name+' +p -lk -o h2ch4_o -m h2ch4_m -L h2ch4_lbl.nc' + '\n')
f.write('prep_spec <<EOF'+ '\n')
f.write(file_name+ '\n')
f.write('a'+ '\n')
# Select block 19 (CIA data)
f.write('19'+ '\n')
f.write('y'+ '\n')
f.write('h2ch4_o'+ '\n')
f.write('-1'+ '\n')
f.write('EOF'+ '\n')
# Remove faulty characters
f.write("sed -i -e 's/\*\*\*\*\*/0/g' "+file_name+'\n')
f.write("sed -i -e 's/\*\*\*//g' "+file_name+'\n')
f.write("sed -i -e 's/            NaN/0.000000000E+00/g' "+file_name+'\n')

#####################

# Add to spec file with prep_spec
f.write('prep_spec <<EOF'+ '\n')
# Select spectral file
f.write(file_name+ '\n')
# Append
f.write('a'+ '\n')
# Thermal source function
f.write('6'+ '\n')
f.write('n'+ '\n')
# Select table fit
f.write('T'+ '\n')
# Temperature range in K
f.write('100 4000'+ '\n')
# Number of points
f.write('100'+ '\n')

# Solar spectrum
f.write('2'+ '\n')
# No filter function
f.write('n'+ '\n')
# Path to spectrum data
f.write(dir_socrates+'data/solar/kurucz_95'+ '\n')
# Assign flux outside data range to bands on edge
f.write('y'+ '\n')

# Exit
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# Close
f.close()
os.chmod('gen_spec_file',0o777)

#######################

# Run script
os.system('./gen_spec_file')

# Remove auxiliary files
os.system('rm -rf *_lbl')
os.system('rm -rf *_lbl.nc')
os.system('rm -rf *_m')
os.system('rm -rf *_o')
os.system('rm -rf *_o.nc')
os.system('rm -rf *_l')
os.system('rm -rf *h2o_*')
os.system('rm -rf *co2_*')
os.system('rm -rf *ch4_*')
os.system('rm -rf *co_*')
os.system('rm -rf *n2_*')
os.system('rm -rf *o2_*')
os.system('rm -rf *h2_*')
